version: "3.1"
services:

    assembleia-database:
      image: postgres:latest
      container_name: assembleia-database
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=assembleia
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=assembleia

    assembleia-app:
      build: docker/php
      container_name: assembleia-app
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    assembleia-webserver:
      image: nginx:alpine
      container_name: assembleia-webserver
      working_dir: /application
      depends_on:
        - assembleia-app
      volumes:
        - .:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    assembleia-composer:
      image: composer:latest
      container_name: assembleia-composer
      working_dir: /application
      command: install
      depends_on:
        - assembleia-app
      volumes:
        - .:/application
